@startwbs dinnerを作る
title カレーを作る
*[#Pink] カレーを作る
**[#SkyBlue] 米を炊く
***[#Yellow] 米を研ぐ\n作業時間5分
***[#Yellow] 炊飯器で炊く\n作業時間55分
**[#SkyBlue] 下ごしらえ
***[#yellow] 人参を切る\n作業時間5分 
***[#yellow] じゃがいもを切る\n作業時間5分
***[#yellow] 玉ねぎを切る\n作業時間5分
***[#yellow] 鶏肉を切る\n作業時間5分
**[#SkyBlue] カレーを作る
***[#Yellow] 鶏肉と野菜を軽く炒める\n作業時間5分
***[#Yellow] 水を入れて煮込む\n作業時間20分
***[#yellow] カレールーを入れて弱火で煮込む\n作業時間15分
@endwbs