@startwbs dinnerを作る
title 夕食作る 
*[#Pink] 夕食を作る
**[#SkyBlue] 買い出し
***[#Yellow] 銀行でお金を下す担当\n太郎 作業時間 20分
***[#Yellow] ニンジン、ジャガイモ、セロリ\n玉ねぎ、カレールー、鶏肉、キャベツを\nスーパーで買う\n担当 太郎 作業時間 20分
**[#SkyBlue] 作る
*** カレーを作る\n担当 花子 作業時間 65分
*** コールスローを作る\n担当 次郎 作業時間 25分
*** コンソメスープを作る\n担当 太郎 作業時間 45分
**[#SkyBlue] 食べる準備をする
***[#Yellow] 腹筋をする\n担当 太郎 作業時間 10分
***[#Yellow] お皿を準備する\n担当 花子 作業時間 10分
@endwbs