@startwbs dinnerを作る
title コールスロー作る 
*[#Pink] コールスローを作る
**[#SkyBlue] 下ごしらえ
***[#Yellow] キャベツを千切りする\n作業時間5分
***[#Yellow] 切ったキャベツをボウルに入れ、\n塩をふりかけて軽くもむ\n作業時間5分
***[#Yellow] 5分ほど置いてから、出てきた水分をしっかり絞る\n作業時間5分
**[#SkyBlue] ドレッシングを作る
***[#Yellow] 別のボウルにマヨネーズ：大さじ３、\nレモン汁：大さじ１、砂糖：小さじ１、\nこしょう：少々を入れてよく混ぜます。\n作業時間5分
**[#SkyBlue] 完成
***[#Yellow] キャベツにドレッシングをかけて、\n冷蔵庫で冷やす\n作業時間5分
@endwbs