@startwbs dinnerを作る
title 夕食作る 
*[#Pink] 夕食を作る
**[#SkyBlue] 買い出し
***[#Yellow] 銀行でお金を下す
***[#Yellow] カレー、ニンジン、ジャガイモ、\n玉ねぎ、カレールー、鶏肉、キャベツを\nスーパーで買う
**[#SkyBlue] 作る
*** カレーを作る
*** コールスローを作る
*** コンソメスープを作る
**[#SkyBlue] 食べる準備をする
***[#Yellow] 腹筋をする
***[#Yellow] お皿を準備する
@endwbs