@startuml sample
start
fork
  :銀行でお金を下す
  担当 向口 作業時間 20分;
  :カレー、ニンジン、ジャガイモ、玉ねぎ、セロリ\nカレールー、鶏肉、キャベツをスーパーで買う\n担当 向口 作業時間 20分;
end fork
fork
  :カレーを作る
  担当 高木 作業時間 65分;
fork again
  :コールスローを作る
  担当 細田 作業時間 25分;
fork again
  :コンソメスープを作る
  担当 向口 作業時間 45分;
end fork
fork
  :腹筋をする
  担当 向口 作業時間 10分;
fork again
  :お皿を準備する
  担当 高木 作業時間 10分;
end fork
stop
@enduml
