@startuml カレー作り
start
fork
  :米を研ぐ\n作業時間5分;
fork
  :米を炊く\n作業時間55分;
fork again
  :人参を切る\n作業時間5分;
  :じゃがいもを切る\n作業時間5分;
  :玉ねぎを切る\n作業時間5分;
  :鶏肉を切る\n作業時間5分;
  :鶏肉と野菜を炒める\n作業時間5分;
  :水を入れて煮込む\n作業時間20分;
  :カレールーを入れて弱火で煮込む\n作業時間15分;
end fork
stop
@enduml