@startuml sample
start
fork
  :銀行でお金を下す
  　担当 畠山 作業時間 30分;
fork again
  :モジュール設計
  　担当 盛田 作業時間 20分;
end fork
fork
  :player.py実装
  　担当 向口 作業時間 30分;
  :test_player.py
  　担当 向口 作業時間 30分;
fork again
  :computer.py実装
  　担当 畠山 作業時間 30分;
  :test_computer.py
  　担当 畠山 作業時間 30分;
fork again
  :janken_judge.py実装
  　担当 藤原 作業時間 30分;
  :test_janken_judge.py
  　担当 藤原 作業時間 30分;
fork again
  :janken.py実装
  　担当 盛田 作業時間 60分;
end fork
fork
  :test_janken.py
  　担当 盛田 作業時間 60分;
end fork
stop
@enduml
