@startuml コールスロー作り
start
fork
  :キャベツを千切りする\n作業時間5分;
  :切ったキャベツをボウルに入れ、\n塩をふりかけて軽くもむ\n作業時間5分;
  :5分ほど置いてから、出てきた水分をしっかり絞る\n作業時間5分;
  :別のボウルにマヨネーズ：大さじ３、\nレモン汁：大さじ１、砂糖：小さじ１、\nこしょう：少々を入れてよく混ぜます。\n作業時間5分;
  :キャベツにドレッシングをかけて、\n冷蔵庫で冷やす\n作業時間5分;
end fork
stop
@enduml